name: Test

on:
  push:
    branches: [ testJC ]

jobs:
  stuff:
    runs-on: ubuntu-latest

    steps:
      - name: Print trucs
        run: |
          echo "Hello World!"
          echo "truc2 "
          echo "${{secrets.MAVEN_GPG_PRIVATE_KEY}}" | sed 's/./& /g'
          
